version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    env_file:
      - .env

volumes:
  postgres_data:
